"""Source-grounded overview content. Historical values are not current forecasts."""
DETAILS = {
'bayesian-housing': {
'abstract':'Using 14,200 cleaned Buenos Aires property listings, I compared three Bayesian price regressions with different treatments of unusual observations. A mixture model that distinguishes inliers from outliers ranked best in the saved predictive comparison, although influential observations triggered diagnostic warnings. Rooms and floor area alone left substantial price variation unexplained.',
'sections':[('The modeling question','An expensive property can reflect a different market segment, an unusual observation or a poorly specified model. I held the predictors constant—rooms and total surface area—and changed the likelihood: Normal errors, Student-t errors and an inlier/outlier mixture.'),('What changed with the likelihood','The mixture specification ranked ahead of the other models in the report’s PSIS-LOO comparison. Student-t errors did not improve on the Normal specification. This is a conditional ranking: influential observations made the mixture’s leave-one-out estimates unstable, so the diagnostic warning belongs alongside the apparent improvement.'),('What I would improve next','Neighborhood and property type are plausible missing predictors. Adding them would help distinguish genuinely unusual properties from systematic differences between submarkets. The current analysis evaluates modeling choices; it is not a validated appraisal tool.')],
'figure':('figures/cell-12-0.png','Rooms, area and price in the project dataset','Saved exploratory output. Relationships and outliers motivate the competing likelihoods.'),
'rows':[['Normal','One residual scale','Baseline fit'],['Student-t','Heavy-tailed errors','No improvement in the reported comparison'],['Mixture','Separate inlier/outlier variation','Best reported ranking; influential-point warnings']], 'headers':['Specification','Treatment of unusual observations','Result']},
'social-networks': {
'abstract':'I built an agent-based model of feedback between social isolation, algorithmic exposure, and weakening friendship ties. Monte Carlo experiments compare three interventions on a common network model. Increasing the effectiveness of social support produced the largest reduction in simulated isolation, while saturation of ideological drift exposed an important limitation of the outcome measure.',
'sections':[('From individual rules to network behavior','The baseline uses 800 agents on a sparse friendship network with an expected degree near twelve. Isolation affects exposure; exposure affects ideological drift; divergence and isolation weaken ties. The model runs for 80 time steps, and repeated runs describe variation under those assumptions.'),('Interventions under common assumptions','I separately reduced maximum amplification from 0.60 to 0.35, increased support effectiveness from 0.25 to 0.40, and strengthened friends’ corrective influence from 0.60 to 0.85. Support produced the largest reduction in isolation in these simulations. These parameter changes are scenario experiments, not empirically estimated treatment effects.'),('A result that challenges the model','Mean drift often approached its upper bound of one. Once an outcome saturates, it becomes less useful for distinguishing interventions. This motivates revisiting the state dynamics and calibration before using the model to inform policy.')],
'figure':('figures/cell-14-1.png','Monte Carlo intervention outcomes with uncertainty intervals','Saved simulation output. Intervals describe Monte Carlo uncertainty, not uncertainty about real-world intervention effects.')},
'multilevel-scores': {
'abstract':'This project reconstructs annual test-score distributions when only grouped histograms, with different bin boundaries, are available. I compared separate and hierarchical Bayesian models using bin probabilities rather than treating bin midpoints as individual scores. Pooling changed estimates relatively little; distributional assumptions mattered more to the predictive fit.',
'sections':[('Keep the information the bins actually contain','Scores lie between zero and 1,500. For each year, the likelihood uses the probability that a score falls within each reported interval. Integrating the distribution over those boundaries lets years with different histograms enter a common model without inventing individual records.'),('Does partial pooling change the comparison?','Separate Normal models and a hierarchical Normal model produced similar estimates, with modest shrinkage for 2023. Large cohort counts leave less scope for pooling to alter the results. Similar estimates, however, do not establish that the Normal likelihood fits well.'),('Check shape as well as location','Predictive checks revealed discrepancies in the score bins. A hierarchical logit-normal model accommodates bounded, asymmetric distributions. Its transformed location, 1,500 × sigmoid(mu), is a median—not the arithmetic mean. The readable notebook flags the original labeling error explicitly.')],
'figure':('figures/cell-17-24.png','Hierarchical Normal posterior predictive checks by year','Saved notebook output. Comparing fitted and observed bin counts tests the distributional assumption directly.')},
'movie-preferences': {
'abstract':'I explored whether movie posters and text improve preference prediction beyond structured metadata, aligning 568 titles from 615 collected ratings. Dimensionality reduction and clustering showed that additional modalities did not automatically produce clearer structure. A review identified preprocessing leakage in the original classifier evaluation; the public notebook now uses fold-local pipelines, with a clean rerun still outstanding.',
'sections':[('Align the representations before comparing them','The analysis combines 36 metadata features, 2,048-dimensional ResNet-50 poster embeddings and TF-IDF/SVD text representations. PCA, ICA, clustering, canonical correlation and modality ablations examine what each representation adds.'),('More features did not mean clearer groups','The first ten metadata principal components explained 59.7% of variance. A four-cluster metadata solution had a silhouette score of 0.194; the joint representation was approximately −0.002 and included a singleton cluster. These exploratory results offer little support for well-separated preference groups.'),('Evaluation is part of the result','The original classifier preprocessing was fitted before the train/test split. Its reported predictive scores therefore cannot be treated as validated generalization performance. The public notebook replaces the primary comparison with preprocessing inside repeated stratified cross-validation; those revised results are not yet available.')],
'figure':('figures/metadata-pca.png','Metadata principal-component projection','Original exploratory projection; it is not evidence of out-of-sample predictive accuracy.'),
'rows':[['Collected ratings','615'],['Aligned titles','568'],['Metadata features','36'],['Poster embedding dimensions','2,048']], 'headers':['Representation','Size']},
'dna-inference': {
'abstract':'I developed an Approximate Bayesian Computation workflow for evaluating related versus unrelated pedigree hypotheses from DNA-sharing summaries. Across eleven pedigrees, repeated cross-validation and label-permutation checks examined how well the constructed reference banks could be distinguished. The project emphasizes probabilistic evidence and the limits of transferring simulation performance to humanitarian identification cases.',
'sections':[('Compare hypotheses through simulated evidence','The workflow simulates related individuals under a pedigree, builds an unrelated reference bank, summarizes shared identity-by-descent segments and uses rejection ABC to estimate support for competing hypotheses. The reference population and calibration choices are part of the inferential model.'),('Assess performance without conflating benchmarks','Five repeated cross-validation runs per pedigree evaluated held-out pseudo-observations. Permuting model labels provided a sanity check. The very high internal classification results describe separation between these reference banks; they do not establish real-case identification accuracy.'),('Why the comparison needs care','The likelihood-ratio benchmark and ABC workflow use different information: a smaller marker set versus genome-wide IBD summaries. Their performance difference cannot isolate an advantage of ABC as an algorithm. The scientific contribution is an explicit, testable workflow and a clearer account of its assumptions.')],
'rows':[['Define','Specify related and unrelated hypotheses'],['Simulate','Construct reference banks and IBD summaries'],['Infer','Estimate support using rejection ABC'],['Check','Repeated cross-validation and permuted labels']], 'headers':['Stage','Purpose']},
'huzur': {
'abstract':"After college graduation, my friends scattered across different countries. Our regular card games became considerably harder to organize! I wanted to keep playing Huzur, a popular household card game in Mongolia, but couldn’t find a website where we could play together. So I built one. The platform supports two to five players, online multiplayer lobbies, and an AI opponent I'm continuously improving.",
'sections':[('A playable system and an evaluation loop','Players can create accounts, join lobbies and play local human/AI matches. Cloudflare Workers and D1 support persistent accounts, match state and records. Decision snapshots and exports connect the application to subsequent analysis.'),('Information boundaries shape the AI','The opponent combines strategic heuristics, lookahead and exact two-player endgame search. Public-information guards restrict the decision inputs; self-play supports comparisons between policies. Strong simulated play alone does not establish performance against human opponents.'),('What remains to build','The documented roadmap includes server-side rules validation, realtime transport and personalized policies. The current implementation is a working platform with an evaluation foundation, rather than a completed competitive multiplayer service.')],
'rows':[['Play','Browser rules and local human/AI seats'],['Persist','Accounts, lobbies and match records in D1'],['Observe','Decision snapshots and structured exports'],['Evaluate','Offline self-play and policy comparison']], 'headers':['Layer','Implementation']},
'forum': {
'abstract':'Forum is a team-built platform that turns class recordings into searchable transcripts and structured notes. I focused on the relational database and data-integrity testing. The application connects course access, recording uploads, transcription and note generation, with explicit processing states and preservation of transcripts if a later stage fails.',
'sections':[('A workflow that can fail in stages','Recording uploads pass through FFmpeg audio extraction, Whisper transcription and AI note generation. Keeping the transcript separate from the generated notes allows a useful intermediate result to survive a downstream failure.'),('My contribution: the data underneath the interface','My work focused on relational storage and data-integrity testing. Courses, memberships, sessions and their generated artifacts need consistent relationships so that search and access operate on the right records.'),('What the demonstration establishes','The repository and linked demo show a course application built with Flask, React and SQLite. This is a team project; it is not a claim of sole authorship or a measured production deployment.')],
'rows':[['Access','Course membership scopes recordings and search'],['Process','Upload → audio → transcript → structured notes'],['Recover','Track processing state and preserve completed stages'],['Retrieve','Search course material and open the underlying session']], 'headers':['Concern','Design']},
'wrigley': {
'abstract':'I evaluated a $3 billion debt-funded payout by separating the tax shield from borrowing costs and expected financial distress. The case’s $1.2 billion no-distress benefit falls to $732 million in the base distress scenario. A smaller $1.83 billion recapitalization offers less modeled value but stronger interest coverage, illustrating why the largest modeled payout need not be the preferred financing policy.',
'sections':[('Value the financing benefit and its cost','The APV analysis adds the debt tax shield and subtracts expected distress costs. Changing the assumed loss conditional on distress reduces modeled net value from $732 million to $576 million. These are scenario estimates, not observed shareholder gains.'),('Debt capacity constrains the recommendation','At $3 billion of debt, modeled interest coverage is about 1.2 times. The proposed $1.83 billion alternative raises coverage to roughly 2.2 times and produces about $520 million of net value under the case assumptions.'),('Do not confuse EPS with value','A repurchase raises modeled EPS relative to a dividend by reducing shares outstanding. That denominator change does not itself create enterprise value. The analysis also considers how tender participation changes family voting control.')],
'rows':[['$3.00B debt','$732M','1.2×'],['$1.83B debt','$520M','2.2×']], 'headers':['Recapitalization','Modeled net value','Interest coverage'],
'bars':('Value after distress assumptions · $ millions',[['Tax shield before distress',1200],['Base net benefit',732],['Higher-loss net benefit',576]])},
'coreweave': {
'abstract':'In an April 2025 team valuation, we combined discounted cash flow, public comparables and precedent transactions for a capital-intensive AI infrastructure business. The methods produced widely different estimates: a $10-per-share base DCF and a $22 synthesis across methods. The analysis makes the dependence on financing, investment and distant cash flows visible rather than treating a single estimate as definitive.',
'sections':[('Separate the valuation methods','The base DCF uses a 12.2% discount rate and 2.6% terminal growth. Public comparables and precedent transactions supply different reference points, with differences in company selection and transaction context.'),('Why the spread matters','Capital expenditure, working capital and long-run cash generation determine how revenue growth converts into equity value. Segment-based comparable adjustments introduce additional judgment. The estimates below are selected central outputs from distinct methods, not confidence bounds.'),('Scope of the conclusion','This was a team course analysis by Undral Ganbaatar, Shazil Farukh and Anne Behme. All estimates refer to the April 2025 report; they are not a current valuation or investment recommendation.')],
'bars':('Selected estimates · dollars per share',[['Base DCF',10],['Public comparables median',8.02],['Precedent transactions median',33.99]]),
'rows':[['DCF discount rate','12.2%'],['Terminal growth','2.6%'],['Report synthesis','$22 per share']], 'headers':['Assumption or output','Report value']},
 'toyota': {
'abstract':'This historical case examines how Toyota’s financial policy relates to production geography, liquidity and currency exposure. Peer ratios place Toyota’s 2011 consolidated debt-to-assets ratio at 63%, but differences in financing subsidiaries limit a simple leverage ranking. The analysis links financial capacity to the operating structure behind the ratios.',
'sections':[('Start with comparable definitions','The report compares automakers in the 2010–2011 case setting. Consolidated balance sheets include both manufacturing and financial services, so debt supports different activities across firms.'),('Connect the balance sheet to operations','Domestic production creates different currency and cost exposures from production closer to regional demand. The case considers geographic flexibility alongside liquidity and leverage, rather than treating financial ratios as an isolated scorecard.'),('Interpret the peer comparison narrowly','The chart describes consolidated accounting ratios in the source report. It does not establish that a company with lower consolidated debt necessarily has lower manufacturing risk or a superior current financial policy.')],
'bars':('2011 consolidated debt / assets · %',[['Toyota',63],['Volkswagen',75],['Ford',92],['General Motors',73],['Hyundai',63]])},
'aditya-birla': {
'abstract':'I developed two international capital-allocation proposals: an India–UAE SME payments business and a low-carbon cement investment. Parent-level DCF models yield positive base-case NPVs for both, but terminal value accounts for a substantial share of their economics. The analysis distinguishes attractive forecast outputs from the execution and remittance assumptions needed to produce them.',
'sections':[('Value cash received by the parent','The forecasts adjust for ownership and remittances rather than equating project cash generation with parent cash receipts. Payments assumes a 70% ownership share; the cement proposal applies a 90% remittance assumption.'),('Compare scale and dependence on the terminal period','The payments proposal requires 70 crore of initial investment and produces a modeled NPV of 190.5 crore. Cement requires 375 crore and produces 485.1 crore. Discounted terminal values of 195.51 and 617.3 crore respectively show how strongly continuation assumptions influence the result.'),('Decision under uncertainty','These are proposed investments, not implemented projects. A decision would require testing volumes, margins, cross-border execution and terminal assumptions, including scenarios where growth or cash remittance falls short.')],
'rows':[['SME payments','70','190.5','195.51'],['Low-carbon cement','375','485.1','617.3']], 'headers':['Proposal','Initial investment','Parent NPV','PV of terminal value'], 'table_note':'All monetary values in INR crore; source report base cases.'},
'astral': {
'abstract':'The Astral Records case combines declining margins with a growth plan and an equipment decision. Under the forecast, adding a $1 million machine raises two-year financing needs from roughly $741,000 to $1.7 million. Its incremental NPV is only about $10,600 under the working-capital assumptions, making financing capacity and sensitivity central to the decision.',
'sections':[('Forecast growth through the balance sheet','Operating margin fell from 24.7% in 1991 to 17.1% in 1993. The forecast assumes 15% sales growth, but receivables, inventory, debt servicing and capital expenditure determine how much external financing that growth requires.'),('Compare purchase timing, not purchase versus nothing','The capital-budgeting comparison evaluates buying the machine now against replacement later. Its small positive incremental NPV depends on working-capital benefits; it should not be read as an unconditional case for immediate investment.'),('Funding and value answer different questions','A positive NPV does not ensure the firm can comfortably finance the project. The case places the incremental valuation alongside the much larger funding requirement.')],
'bars':('Two-year financing requirement · $ millions',[['Without equipment purchase',0.741],['With equipment purchase',1.7]])},
'science-technology': {
'abstract':'I assessed a plan to accelerate sales growth to 30% from a historical rate near 12%. The forecast improves the cash conversion cycle but still increases working capital from $147 million to $425 million. The central result is that efficiency gains can coexist with rising financing needs when the business expands quickly.',
'sections':[('Growth consumes cash before it produces it','Receivables and inventory scale with the business. Faster turnover reduces cash tied up per dollar of sales, but a sufficiently large sales increase can still raise total working capital.'),('Test the plan’s operational assumptions','The case forecast reduces the cash conversion cycle from 375 days in 1984 to approximately 281 in 1989. Those improvements are assumptions in the plan, not achievements already observed.'),('Evaluate financing alongside profitability','Projected income rises while the cash forecast becomes more strained. Inventory execution and reliance on short-term borrowing are therefore central to whether the growth plan is credible.')],
'rows':[['Working capital','$147M','$425M'],['Cash conversion cycle','375 days','≈281 days']], 'headers':['Measure','1984 case baseline','1989 forecast']},
'rvd-ai': {
'abstract':'Using the venture-capital method, I examined how a larger initial investment changes the ownership required by an investor. At the report’s fixed $4.33 million post-money estimate, raising $2.5 million implies a 57.7% investor stake; raising $3.5 million implies 80.8%. The analysis exposes the dilution embedded in the growth and exit assumptions.',
'sections':[('Work backward from an exit scenario','The model assumes a $1.49 billion addressable market, 2% market share, a 10% earnings margin, an exit P/E of eleven and a 50% required return over five years. These assumptions produce the valuation used for both funding comparisons.'),('Hold valuation constant to isolate the funding tradeoff','The larger raise provides another $1 million but reduces the residual founder share from approximately 42.3% to 19.2%. These are simplified ownership calculations before any subsequent rounds or additional dilution.'),('What the calculation does not establish','Market size is not revenue, and assumed market share is not demonstrated traction. The ownership outcomes are scenario results rather than negotiated financing terms.')],
'bars':('Investor ownership at fixed valuation · %',[['$2.5M raise',57.73],['$3.5M raise',80.82]])},
'optiguard': {
'abstract':'I modeled how antidilution and liquidation preferences change venture-financing outcomes beyond the headline valuation. In a $15 million exit scenario with an option reserve, the investor receives approximately $6.15 million under a conventional preference versus $9.52 million under a participating preference. The economic difference comes from contractual rights, not a change in the exit value.',
'sections':[('Model the capitalization before comparing terms','The analysis starts with a $5.7 million Series A investment at $4 per share, then considers a hypothetical $7.8 million round at $3. Weighted-average antidilution adjusts conversion terms; it does not simply guarantee an unchanged ownership percentage.'),('Follow the payout waterfall','A conventional preference requires comparing the preference payout with conversion. A participating preference adds participation in residual proceeds. At the same exit value, that distinction materially reallocates proceeds between investors and founders.'),('Keep the scenario explicit','The figures depend on the modeled reserve, capitalization and exit assumptions. They do not describe an executed investment or a guaranteed recovery.')],
'bars':('Investor proceeds at a $15M exit · $ millions',[['Conventional preference',6.154621],['Participating preference',9.515865]])},
'freddo': {
'abstract':'This expansion case connects a marketing proposal with working-capital discipline. The operating model uses a 70-day cash conversion cycle; reducing inventory from 60 to 30 days would lower it to 40 days if receivables and payables remain unchanged. The exercise makes explicit which operational changes the expansion economics would need to support.',
'sections':[('Translate operations into cash tied up','The baseline cash cycle is 20 receivable days plus 60 inventory days minus ten payable days. The target changes inventory rather than assuming all three components improve simultaneously.'),('Separate the operating target from the valuation','The campaign model reports an NPV of approximately $72,015 under its assumptions. The original valuation uses the 70-day cycle; the 40-day figure is a proposed operational target, not an improvement already included or achieved.'),('What would need validation','Conversion, cannibalization, shipping costs and local production feasibility drive the business case. The projected benefits are estimates for a course proposal, not measured savings or realized expansion results.')],
'rows':[['Receivables','20','20'],['Inventory','60','30'],['Payables (subtract)','10','10'],['Cash conversion cycle','70','40']], 'headers':['Component','Model baseline · days','Operational target · days']}
}
DETAILS['predator-prey'] = {
'abstract':'I simulated a spatial predator–prey ecosystem to explore how local growth, hunting, mortality, and movement produce coexistence or collapse. Parameter sweeps reveal regimes that are difficult to infer from a single trajectory. Comparing the simulation with mean-field relationships helps distinguish population-level balance from the spatial processes that sustain it.',
'sections':[('Let local interactions produce the pattern','The model represents bunny and fox densities on a 200 × 200 toroidal grid over 1,000 time steps. Logistic prey growth, predation, reproduction, mortality, and diffusion update each cell. These are real-valued densities, not individually tracked animals.'),('Vary the rules instead of trusting one run','I varied predator growth, consumption, and relative mobility to examine coexistence and extinction regions. The heatmaps describe outcomes under the tested parameters and time horizon. They are not estimates of real ecosystems’ extinction probabilities.'),('Check what the average leaves out','The report derives mean-field relationships and compares simulated growth with predation in a stationary regime. Agreement in an average balance does not mean the local densities are uniform. Spatial patches and oscillations remain important to interpreting the model.')],
'figure':('figures/cell-7-0.png','Parameter sweep of bunny and fox densities','Saved simulation output. The parameter grid identifies different regimes within this model.'),
'video':('predator-prey','Bunnies on the left, foxes on the right','Animation supplied with the project, showing local densities over simulation time. Green and red intensities represent bunny and fox densities respectively; the panels use separate color scales. This is one simulated trajectory, not an empirical population map.')}
DETAILS['airport-security'] = {
'abstract':'This team project models airport security as a system of interacting queues. I implemented a discrete-event simulation with shortest-queue routing and a shared senior officer for secondary screening, then compared simulated performance with queueing approximations. The comparison exposes why adding primary stations alone may not remove congestion created by a shared resource.',
'sections':[('Model the shared resource explicitly','Passengers arrive at ten per minute and choose the shortest queue. Primary screening takes about thirty seconds on average, while secondary screening introduces another dependency. A shared officer couples the stations, so treating extra screening as independent service time can miss the bottleneck.'),('Compare simulation with theory','The notebook tests simplified queueing approximations against simulated waiting times and queue lengths. The report then summarizes eighty runs of the main scenario, showing how congestion falls as station count increases.'),('A recommendation needs a decision rule','The report favors eight stations as a practical compromise between waiting and utilization. That is a judgment under the scenario, not a cost-optimal staffing result: labor costs, service targets, transient behavior, and the secondary-screening design would need further analysis.')],
'rows':[['6','52.03 ± 3.68','519.51 ± 36.27'],['7','7.69 ± 1.31','77.40 ± 13.16'],['8','3.22 ± 0.58','32.35 ± 5.85'],['9','2.15 ± 0.45','21.54 ± 4.64'],['10','1.19 ± 0.33','11.98 ± 3.30']],
'headers':['Primary stations','Mean wait · minutes','Mean queue length'],
'table_note':'Source: report Table 1, eighty simulation runs. Values show reported means ± 95% confidence-interval half-widths; these describe simulation uncertainty.',
'figure':('figures/cell-30-0.png','Queueing approximations compared with shortest-queue simulation','Saved notebook comparison with a single shared officer. Theoretical curves use different approximations.')}
DETAILS['social-networks']['video']=('social-network','Watch the friendship network evolve','Nodes represent simulated agents; edges represent friendship ties. Node color shows ideological drift D on a zero-to-one scale. The title tracks time, mean drift D, mean isolation I, and the remaining edge count. This illustrative run is separate from the full Monte Carlo comparison below.')

DETAILS['ebike-survey'] = {
'markdown_source': 'ebike-survey/analysis-draft.md',
'source_links': [('Read original report (PDF)', 'survey-report.pdf')]
}
